export default {
  // align: 'center',
  // cancelBtnText: '关 闭',
  // editTitle: 'edit test',
  // labelWidth: 145,
  // tip: false,
  // menu: false,
  // header: false,
  // updateBtn:false,
  // border: true,
  // selection: true,
  // selectable: row => row.$cellEdit,
  column: [
    {
      label: "字段类型",
      prop: "propertyType",
      type: "select",
      columnJson: false,
      width: 160,
      rules: [{required: true, message: '字段类型为空', trigger: 'change'}],
      dicData: [
        {label: 'String', value: 'java.lang.String'},
        {label: 'Boolean', value: 'java.lang.Boolean'},
        {label: 'Byte', value: 'java.lang.Byte'},
        {label: 'Integer', value: 'java.lang.Integer'},
        {label: 'Long', value: 'java.lang.Long'},
        {label: 'Double', value: 'java.lang.Double'},
        {label: 'BigDecimal', value: 'java.math.BigDecimal'},
        {label: 'Date', value: 'java.util.Date'},
        {label: 'LocalDate', value: 'java.time.LocalDate'},
        {label: 'LocalDateTime', value: 'java.time.LocalDateTime'},
        {label: 'Object', value: 'java.util.Object'}
      ],
    },
    {
      label: "字段名",
      prop: "prop",
      type: "input",
      width: 160,
    },
    {
      label: "字段显示名",
      prop: "label",
      type: "input",
      width: 160,
      rules: [{required: true, message: '字段显示名为空', trigger: 'blur'}],
    },
    {
      label: "表单类型",
      prop: "type",
      type: "select",
      width: 160,
      rules: [{required: true, message: '表单类型为空', trigger: 'change'}],
      dicData: [
        {label: '单行文本', value: 'input'},
        {label: '多行文本', value: 'textarea'},
        {label: '数字输入框', value: 'number'},
        {label: '下拉选项', value: 'select'},
        {label: '树形下拉选项', value: 'tree'},
        {label: '日期框', value: 'datetime'},
        {label: '开关框', value: 'switch'}
      ],
    },
    {
      label: "表单默认值",
      prop: "value",
      type: "input",
      width: 160,
    },
    {
      label: "栅格占据的列数",
      prop: "span",
      type: "number",
      width: 160,
      blur: (event, value) => value.span = (value.span > 24 || value.span < 1) ? 12 : value.span
    },
    {
      label: "表单排序",
      prop: "order",
      type: "number",
      width: 160,
      min: -99,
      max: 99,
      precision: 0,
    },
    {
      label: "新增是否显示",
      prop: "addDisplay",
      type: "switch",
      width: 110,
      dicData: [],
      dataType: 'boolean',
    },
    {
      label: "编辑是否显示",
      prop: "editDisplay",
      type: "switch",
      width: 110,
      dicData: [],
      dataType: 'boolean',
    },
    {
      label: "查看是否显示",
      prop: "viewDisplay",
      type: "switch",
      width: 110,
      dicData: [],
      dataType: 'number',
    },
    {
      label: "新增是否禁止",
      prop: "addDisabled",
      type: "switch",
      width: 110,
      dicData: [],
      dataType: 'boolean',
    },
    {
      label: "编辑是否禁止",
      prop: "editDisabled",
      type: "switch",
      width: 110,
      dicData: [],
      dataType: 'boolean',
    },
    {
      label: "是否必填",
      prop: "isRequired",
      type: 'switch',
      width: 110,
      dicData: [],
      dataType: 'number',
    },
    {
      label: "是否导出",
      prop: "isExport",
      type: 'switch',
      columnJson: false,
      width: 110,
      dicData: [],
      dataType: 'number',
    },
    {
      label: "是否打印",
      prop: "isPrint",
      type: 'switch',
      columnJson: false,
      width: 110,
      dicData: [],
      dataType: 'number',
    },










    // {
    //   label: "表单验证规则",
    //   prop: "rules",
    //   span: 24,
    //   order: -1,
    //   type: "textarea",
    //   placeholder: '请输入',
    //   editDisplay: false,
    //   hide: true
    // },
    // {
    //   label: "输入框占位文本",
    //   prop: "placeholder",
    //   type: 'input',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '是否可清空',
    //   prop: 'clearable',
    //   type: 'switch',
    //   dicData: [],
    //   dataType: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '最大输入长度',
    //   prop: 'maxlength',
    //   type: 'number',
    //   precision: 0,
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '最小输入长度',
    //   prop: 'minlength',
    //   type: 'number',
    //   precision: 0,
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '输入框行最大行数',
    //   prop: 'maxRows',
    //   type: 'number',
    //   precision: 0,
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '输入框行最小行数',
    //   prop: 'minRows',
    //   type: 'number',
    //   precision: 0,
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '输入框行数',
    //   prop: 'rows',
    //   type: 'number',
    //   precision: 0,
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '最大值',
    //   prop: 'max',
    //   type: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '最小值',
    //   prop: 'min',
    //   type: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '步长',
    //   prop: 'step',
    //   type: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '级联的子节点',
    //   prop: 'cascader',
    //   type: 'input',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '级联的默认选项序号',
    //   prop: 'cascaderIndex',
    //   type: 'input',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '是否可搜索选项',
    //   prop: 'filterable',
    //   type: 'switch',
    //   dicData: [],
    //   dataType: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '是否为远程搜索',
    //   prop: 'remote',
    //   type: 'switch',
    //   dicData: [],
    //   dataType: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '是否多选',
    //   prop: 'multiple',
    //   type: 'switch',
    //   dicData: [],
    //   dataType: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '真实值的时间格式(未完成)',
    //   prop: 'valueFormat',
    //   type: 'select',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '显示值时间格式(未完成)',
    //   prop: 'format',
    //   type: 'select',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '多选时是否将选中值按文字的形式展示',
    //   prop: 'tags',
    //   type: 'switch',
    //   dicData: [],
    //   dataType: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '在显示复选框的情况下，是否严格的遵循父子不互相关联的做法',
    //   prop: 'checkStrictly',
    //   type: 'switch',
    //   dicData: [],
    //   dataType: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '是否可以选择父类',
    //   prop: 'parent',
    //   type: 'switch',
    //   dicData: [],
    //   dataType: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '是否每次只打开一个同级树节点展开',
    //   prop: 'accordion',
    //   type: 'switch',
    //   dicData: [],
    //   dataType: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: '子类全选时勾选值不包含父类',
    //   prop: 'leafOnly',
    //   type: 'switch',
    //   dicData: [],
    //   dataType: 'number',
    //   editDisplay: false,
    //   hide: true,
    // },
    // {
    //   label: "字典编码",
    //   prop: "dictCode",
    //   editDisplay: false,
    //   hide: true,
    // },
  ]
}
